#!/usr/bin/env bash

#         888                       888                d8   
#         888-~88e  e88~~8e  888-~\ 888-~88e   d88~\ _d88__ 
#         888  888 d888  88b 888    888  888b C888    888   
#         888  888 8888__888 888    888  8888  Y88b   888   
#         888  888 Y888    , 888    888  888P   888D  888   
#         888  888  "88___/  888    888-_88"  \_88P   "88_/ 
                                                  
#                slick's x200 herbstluftwm config

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#979797'

# remove all existing keybindings
hc keyunbind --all

# colors
. "/home/slick/.colors/black3"

# bar
 find the panel
   panel=~/.config/herbstluftwm/launch.sh
   for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
        "$panel" $monitor &
done

# startup
pkill xbindkeys
pkill xmodmap
pkill compton
compton &
xrdb ~/.Xresources &
feh --bg-fill ~/.wallpaper.png --no-fehbg &
#wal -R &
xbindkeys &
xmodmap -e "keycode  135 = Super_L Super_R" &
xinput --set-prop 10 "libinput Accel Speed" -0.5 &
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0

# Mod1=alt Mod4=super
Mod=Mod4

# keybindings
hc keybind $Mod-Shift-Delete quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close_or_remove
hc keybind $Mod-Shift-q close_and_remove
hc keybind $Mod-BackSpace remove

# cli
hc keybind $Mod-Return spawn urxvt -name 'slick@x200: ~'
hc keybind $Mod-Shift-Return spawn urxvt -e tmux new-session -s urxvt
hc keybind $Mod-v spawn drawterm
hc keybind $Mod-d spawn dmenu_run -fn kakwafont -p $ -nb '#0f0f0f' -sb '#4a4a4a'
hc keybind $Mod-Shift-d spawn dmenuunicode

# applications
hc keybind $Mod-w spawn waterfox
hc keybind $Mod-Shift-w spawn google-chrome-stable
hc keybind $Mod-t spawn urxvt -e htop
hc keybind $Mod-r spawn urxvt -e ranger
hc keybind $Mod-c spawn urxvt -e calcurse
#hc keybind $Mod-m spawn urxvt -e cmus
hc keybind $Mod-m spawn urxvt -e tmux new-session -s music cmus
hc keybind $Mod-Shift-t spawn urxvt -e irssi
hc keybind $Mod-e spawn mgba-qt

# scripts
hc keybind $Mod-Shift-m spawn /home/slick/Scripts/popup/cover-random.sh
hc keybind $Mod-Shift-c spawn /home/slick/Scripts/popup/calender.sh

# lockscreen
hc keybind Control-Alt-l spawn i3lock -f -i ~/Pictures/hlwm/i3lockX200.png
#hc keybind Control-Alt-l spawn i3lock-fancy -t LOCKED -f AventGarde-Book

# screenshot
hc keybind Print spawn scrot 'scrot_%Y-%m-%d-%S_$wx$h.png'

# padding
#hc pad 0 28 4 4 4
hc pad 0 41 4 4 4
hc set snap_gap 6
hc set window_gap 6

# notepad
hc keybind $Mod-n spawn ~/.config/herbstluftwm/notepad.sh
hc keybind $Mod-Shift-n load '(split vertical:0.500000:0 (split vertical:0.140000:1 (clients vertical:0) (clients vertical:0 0x600009)) (split vertical:0.870000:0 (clients vertical:0) (clients vertical:0)))'

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-y       split   left    0.5
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-i       split   top     0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.01
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# frame and gap
hc keybind $Mod-g cycle_value frame_transparent_width 0 4
hc keybind $Mod-Shift-g cycle_value window_gap 6 0

# layouting
hc keybind $Mod-s floating toggle
hc keybind $Mod-Shift-s spawn ~/.config/herbstluftwm/toggle-single-float.sh
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-b load '(split horizontal:0.670000:1 (clients max:0 0xa00010) (split vertical:0.620000:0 (clients vertical:0 0x1200009) (clients vertical:0 0x800009)))'
#hc keybind $Mod-b load '(split horizontal:0.680000:1 (clients max:0) (split vertical:0.600000:0 (clients vertical:0 0x1400009) (clients vertical:0)))'

# cycle available layouts
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all +1

# tags
tag_names=("" "" "")
tag_keys=( {1..3} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Shift-BackSpace use_previous

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#'
hc set frame_border_normal_color '#'
hc set frame_bg_normal_color '#666666'
hc set frame_bg_active_color '#FFFFFF'
hc set frame_normal_opacity 50
hc set frame_active_opacity 50
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0

hc attr theme.active.color "$color2"
hc attr theme.normal.color "$color2"
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color gray
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#'
hc attr theme.active.outer_color '#'
hc attr theme.background_color '#'

hc set frame_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'
emit_hook
